version: '3.8'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ckb
      POSTGRES_PASSWORD: password
      POSTGRES_DB: charitykaraoke
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080